---
title: "Project 1"
author: "Nate Mosley"
date: "March 20, 2017"
output: html_document
---

#This is the markdown document for Reproducible Research - Project 1.

###Loading and preprocessing the data
```{r}
tempfile <-"data.zip"
    if(!file.exists(tempfile)){
      fileUrl <- "https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip"  
      download.file(fileUrl,tempfile)  
    }
if(!file.exists("activity.csv")){
      unzip(tempfile)
}
df<-read.csv("activity.csv", head=TRUE)
df$date<-as.Date(as.character(df$date),format="%Y-%m-%d")
echo=TRUE
```

###What is mean total number of steps taken per day?
```{r}
agg<-aggregate(df$steps, by=list(df$date),FUN=sum,na.rm=TRUE)
hist(agg$x, main = "Activity",xlab="Number of steps taken each day")

stepdaymean<-mean(agg$x)
stepdaymedian<-median(agg$x)
stepdaymean
stepdaymedian
```

###What is the average daily activity pattern?
```{r}
agg2<-aggregate(df$steps, by=list(df$interval),FUN=mean, na.rm=TRUE)
plot(agg2$Group.1, agg2$x, type="l",col="red", main="Activity",xlab="Interval",ylab="Average Steps")
```
